### ISSUE TITLE
Kenda USA/Taiwan RR analysis build rules 

### ISSUE THREAD

**Issue by rpottsoh** [TMSI-LLC/software-discussions#2]
@thetribefan I noticed your recent check in regarding compiler directive for RR Analysis as it pertains to several customers, but specifically Kenda.  For the time being both Kenda systems should be sharing the same directive.  The other customers you mentioned in your comment:

`{_define CooperHSU_China} // this was used for Nexen, Dongfeng Nissan, and Kenda China originally.  I am not sure whether Kenda China is using KendaHSU (which would incorporate KendaUSA requests) or not right now.  2/17/17 meh  This is a note to check on this.`

The two will each have their own directive until such time that they diverge from one another.

**Comment by thetribefan** [comment]
Okay
